defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: "Seryiza: Web Developer"
      header_text_links:
        - text: Главная
          href: /
        - text: Мой Круг
          href: https://moikrug.ru/seryiza
        - text: Игры
          href: https://seryiza.itch.io
        - text: Образование
          href: /education
      footer_icon_links:
        - name: github
          href: https://github.com/Seryiza
        - name: telegram
          href: https://t.me/Seryiza
        - name: vk
          href: https://vk.com/seryiza
        - name: skype
          href: https://join.skype.com/invite/qFsxVPDXItwz
