defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: "Seryiza: Web Developer"
      header_text_links:
        - text: Главная
          href: /
        - text: Резюме
          href: /resume
        - text: Игры
          href: https://seryiza.itch.io
      footer_icon_links:
        - name: github
          href: https://github.com/Seryiza
        - name: telegram
          href: https://t.me/Seryiza
        - name: vk
          href: https://vk.com/seryiza
        - name: instagram
          href: https://www.instagram.com/seryiza/
